AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MyServerlessApp - Login Module using an existing secret from Parameter Store.

Globals:
  Function:
    Runtime: java21
    MemorySize: 512
    Timeout: 30
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    # Configuración de SnapStart: activa SnapStart para todas las funciones
    SnapStart:
      ApplyOn: PublishedVersions

Resources:
  # Define la tabla de DynamoDB
  LoginUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Define la función Lambda
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Esto cambiará más adelante para referenciar a una variable de maven, de forma que al ejecutar
      # sam build para el despliegue, y SAM llame a maven para el build del modulo, inyecte el nombre
      # correcto del jar
      # CodeUri: target/${CodeUriJarName}
      CodeUri: .
      Architectures:
        - x86_64
      Environment:
        Variables:
          MAIN_CLASS: pjserrano.login.LoginApplication
          SPRING_CLOUD_FUNCTION_DEFINITION: loginFunction
          JWT_EXPIRATION: "3600000"
          # Opcional: Configuración explícita de Spring Cloud AWS
          SPRING_CLOUD_AWS_REGION_STATIC: !Ref AWS::Region
      Policies:
        # Define una política de IAM explícita para leer el parámetro de SSM
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - "ssm:GetParameter"
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/login/jwt/secret"
        # Permisos de solo lectura a la tabla de DynamoDB (principio de menor privilegio)
        - Statement:
            - Sid: DynamoDBReadOnlyPolicy
              Effect: Allow
              Action:
                - "dynamodb:GetItem"
              Resource: !GetAtt LoginUsersTable.Arn
      Events:
        LoginApi:
          Type: HttpApi
          Properties:
            Path: /login
            Method: POST

Outputs:
  LoginApiUrl:
    Description: "API Gateway endpoint URL for Login Function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/login"

  LoginUsersTableArn:
    Description: "ARN of the DynamoDB users table"
    Value: !GetAtt LoginUsersTable.Arn
