### Intento de inicio de sesion con credenciales incorrectas

POST {{host}}/{{stageName}}/login
Content-Type: application/json

{
  "username" : "wrong_user",
  "password" : "wrong_password"
}

> {%
    // Escribir un test para verificar el resultado fallido
    client.test("El test ha sido correcto en su resultado esperado", function() {
        const status = response.status;
        client.assert(true, "El login falló con status " + status);
    });
%}