name: CI de Authentication Service
on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'authentication-service/**'
      - 'pom.xml'
  pull_request:
    branches:
      - develop
      - master
    paths:
      - 'authentication-service/**'
      - 'pom.xml'
  merge_group:
    branches:
      - develop
      - master
    paths:
      - 'authentication-service/**'
      - 'pom.xml'

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      module_name: 'authentication-service'